name: fluent_starter
description: MAPID Explorer mobile case study.
version: 1.0.1+2
publish_to: none
resolution: workspace
environment:
  sdk: ">=3.13.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  core_network: any
  core_lifecycle_data: any
  core_location_data: any
  core_design_system: any
  map_data: any
  map_presentation: any
  auto_route: any
  fluent_ui: any
  get_it: any
  injectable: any
  dio: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  injectable_generator: any
  flutter_flavorizr: any
  map_domain: any
  core_location_domain: any
flutter:
  uses-material-design: true
